### ISSUE TITLE
Missing information for `--diamond-path`

### ISSUE THREAD

**Issue by xapple** [Matthijnssenslab/ViPER#8]
The ViPER pipeline seems to offer a classification feature, which is essential in making sense of any viral data. However it is not clear how to use this feature.

The documentation says that one should add the path to a diamond database after `--diamond-path`. Yes, but which database or what kind? Are we supposed to come up with our own collection of taxonomically annotated sequences? What did you use in your research? Any suggestions? Ideally, a default should be provided and should auto-download on the first run to create a smoother user experience.

Currently, I'm not sure how you intend for users to use "ViPER" with no classification database bundled?

**Comment by LanderDC** [comment]
The 'classification' feature of ViPER generates a [Krona](https://github.com/marbl/Krona) chart that's based on a [diamond](https://github.com/bbuchfink/diamond) blastx alignment with a database that contains sequences with an accession number from NCBI. Krona will, based on the accessions of the best 25 hits, get the lowest common ancestor and display this in a pie chart.

In our lab we currently use NCBI's nr database formatted for `diamond`. As the nr database is currently ~300GB, it is undesirable to let it auto-download on the first run. To use the nr database, you will have to download it as a fasta file (see [here](https://ncbiinsights.ncbi.nlm.nih.gov/2024/01/25/blast-fasta-unavailable-on-ftp/) for info on the current best way to generate the complete nr fasta file), and format it to a diamond database with `diamond makedb`. Alternatively, if you're only interested in the viruses in your data, you can only download the virus sequences from the nr database, which will reduce the runtime and database size massively.

I hope this answers your questions? I will update the documentation to make this more clear for other users.

However, if you are looking to reliably identify (novel) viruses, I recommend using the contig output from ViPER and running it through [genomad](https://github.com/apcamargo/genomad).

**Comment by xapple** [comment]
I see. Thanks a lot for your answer. It's very clear now.
In fact it's so well written, that I would suggest you add it into the manual or the `README.md`.
This would greatly help out any new or aspiring bioinformaticians to better grasp how to use the tool.
